### ISSUE TITLE
Create Page With Reccomended/Finetuned Models, Categorized By VRAM Size

### ISSUE THREAD

**Issue by datacrystals** [datacrystals/AIStoryWriter#10]
Might be good to have some suggested models that are each categorized by the different model sizes. That way, users with different VRAM capacities have recommended models to start with. Perhaps we can even create an EasyWrite.py or something that automatically detects this for you? (And auto-downloads them?)

**Comment by LoggeL** [comment]
I've taken the freedom to add a new readme with this issue.
