### ISSUE TITLE
Add Client Wrapper

### ISSUE THREAD

**Issue by datacrystals** [datacrystals/AIStoryWriter#18]
As per the conversation going on in the discussions section - adding a class for the client wrapper so it can be edited to support multiple backends.

**Comment by LoggeL** [comment]
Working on this but it's way bigger than I imagined 🙃

**Comment by datacrystals** [comment]
Haha, thanks for diving in!

Also, looks like my 'improvements' made a bunch of stuff worse, so working
on fixing those lol.

**Comment by LoggeL** [comment]
So you want me to hold off?
Also do you want to chat via Discord/Telegram/...? I don't feel like spamming issues / discussions :D

**Comment by datacrystals** [comment]
Sure, if you send me an email (on the readme), then I'll send you my
discord (just don't want to post it publicly).

And no, please forge ahead - I was just bemoaning my own buggy code. It
shouldn't affect your update.

**Comment by LoggeL** [comment]
I will later try to add Anthropic and maybe OpenAI aswell. Should be doable with the current system now.
