### ISSUE TITLE
Remove OLLAMA Host Requirement

### ISSUE THREAD

**Issue by datacrystals** [datacrystals/AIStoryWriter#36]
We need to make it so that the ollama host is not required and the system can be used without ollama.

**Comment by LoggeL** [comment]
It would be better in general to make every provider optional and only load the requirements when we detect a model of the given provider.

**Comment by datacrystals** [comment]
Agreed - I was thinking that instead of having a host at all, it could be baked into the model 'name' E.g OLLAMA on localhost could be: `ollama://localhost:11434/username/model`, and google could be: `google://gemini-1.5-flash` or something.

Are there any issues that I'm not thinking of with that scheme?

**Comment by LoggeL** [comment]
I like that approach. That should also work with open router as far as I see. I can implement that today if you'd like.

**Comment by datacrystals** [comment]
Yes, please! Thanks for your help.
