### ISSUE TITLE
Optional Multi-Language Support for LLM Story Generator

### ISSUE THREAD

**Issue by LoggeL** [datacrystals/AIStoryWriter#4]
Implement an optional translator layer to enable story creation in multiple languages:

1. Translation of user's story outline from their native language to English
2. Generation of the story in English using the existing Writer
3. Translation of the final story back into the user's original language

Implementation requirements:
- Integration of a specialized translation model capable of handling English and the user's chosen language
- User option to activate this feature when desired

This enhancement would expand the accessibility of the story generator to non-English speaking users while maintaining the core English-based LLM functionality.

**Comment by datacrystals** [comment]
@LoggeL Just a quick question - do you also mean that we should translate the user's base prompt to English, then run the normal generation pipeline too?

I have it translating the end result story to other language right now, but curious about that first part.

**Comment by datacrystals** [comment]
I think I have everything implemented now, if not, feel free to reopen.
