### ISSUE TITLE
Validate ollama model via ollama.show

### ISSUE THREAD

**Issue by LoggeL** [datacrystals/AIStoryWriter#46]
Should resolve more variants (e.g. ":latest")

**Comment by LoggeL** [comment]
Also tackled this in #45

**Comment by datacrystals** [comment]
Hmm, not sure I understand fully what you mean by that - are you suggesting we auto-append `:latest:` to the model when trying to load it if it's not already present?

**Comment by LoggeL** [comment]
> Hmm, not sure I understand fully what you mean by that - are you suggesting we auto-append `:latest:` to the model when trying to load it if it's not already present?

The strategy I used before was to pull the model list. It could return syntax like "llama3", "llama3:8b", "llama3:latest" which I solved with checking for the model and for model`:latest`. It was a kinda hacky solution. Now it uses ollama.show(model) which triggers ollamas internal model resolver which is cleaner imo.

**Comment by datacrystals** [comment]
Gotcha, I see now - that sounds great - I didn't even know OLLAMA had that feature.

**Comment by LoggeL** [comment]
Haha same found it randomly while stumbling through the API docs :P
