### ISSUE TITLE
need help  Do I need to fill in the key? Where do you fill in key specifically?

### ISSUE THREAD

**Issue by Lang123646** [datacrystals/AIStoryWriter#50]
Run to display the problem:
PS F:\aaaaa\AIStoryWriter> & C:/Python312/python.exe f:/aaaaa/AIStoryWriter/Write.py
[5 ] [2024-07-10_20-05-41] Created OLLAMA Interface
DEBUG: Loading Model gemini-1.5-pro from google
Traceback (most recent call last):
  File "f:\aaaaa\AIStoryWriter\Write.py", line 234, in <module>
    Interface = Writer.Interface.Wrapper.Interface(Models)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\aaaaa\AIStoryWriter\Writer\Interface\Wrapper.py", line 23, in __init__
    self.LoadModels(Models)
  File "f:\aaaaa\AIStoryWriter\Writer\Interface\Wrapper.py", line 87, in LoadModels
    raise Exception(
Exception: GOOGLE_API_KEY not found in environment variables

**Comment by LoggeL** [comment]
Copy the .env.example file and rename it to .env file. You can put the API key there, then it should work

**Comment by datacrystals** [comment]
@LoggeL Is that info already in the readme or do you think we should try and make that a bit more clear?

**Comment by LoggeL** [comment]
Definitely something to add to the readme. Let's keep it short so it doesn't clutter too much. Currently traveling feel free to tackle it 😄

**Comment by datacrystals** [comment]
Will do, sounds good.
